//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成.
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MECF.Framework.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等.
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的.
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MECF.Framework.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Account {0} log in 的本地化字符串.
        /// </summary>
        internal static string AccountManager_Login_account_log_In {
            get {
                return ResourceManager.GetString("AccountManager_Login_account_log_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 exit 的本地化字符串.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RF interlock is not satisfied,can not power on 的本地化字符串.
        /// </summary>
        internal static string IoRf_Initialize_RFInterlockIsNotSatisfiedCanNotPowerOn {
            get {
                return ResourceManager.GetString("IoRf_Initialize_RFInterlockIsNotSatisfiedCanNotPowerOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set RF match position c1 :{0} 的本地化字符串.
        /// </summary>
        internal static string IoRf_Initialize_SetRFMatchPositionC10 {
            get {
                return ResourceManager.GetString("IoRf_Initialize_SetRFMatchPositionC10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set RF match position c2 :{0} 的本地化字符串.
        /// </summary>
        internal static string IoRf_Initialize_SetRFMatchPositionC20 {
            get {
                return ResourceManager.GetString("IoRf_Initialize_SetRFMatchPositionC20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set RF power  的本地化字符串.
        /// </summary>
        internal static string IoRf_Initialize_SetRFPower {
            get {
                return ResourceManager.GetString("IoRf_Initialize_SetRFPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System do not support setting match mode. 的本地化字符串.
        /// </summary>
        internal static string IoRf_SetMatchMode_SystemDoNotSupportSettingMatchMode {
            get {
                return ResourceManager.GetString("IoRf_SetMatchMode_SystemDoNotSupportSettingMatchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match position C1 set to {0}  的本地化字符串.
        /// </summary>
        internal static string IoRf_SetMatchPosition_MatchPositionC1SetTo0 {
            get {
                return ResourceManager.GetString("IoRf_SetMatchPosition_MatchPositionC1SetTo0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match position C2 set to {0} 的本地化字符串.
        /// </summary>
        internal static string IoRf_SetMatchPosition_MatchPositionC2SetTo0 {
            get {
                return ResourceManager.GetString("IoRf_SetMatchPosition_MatchPositionC2SetTo0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RF interlock is not satisfied,can not be on 的本地化字符串.
        /// </summary>
        internal static string IoRf_SetPower_RFInterlockIsNotSatisfiedCanNotBeOn {
            get {
                return ResourceManager.GetString("IoRf_SetPower_RFInterlockIsNotSatisfiedCanNotBeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recipe validation failed 的本地化字符串.
        /// </summary>
        internal static string RecipeFileManager_CheckRecipe_RecipeValidationFailed {
            get {
                return ResourceManager.GetString("RecipeFileManager_CheckRecipe_RecipeValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 recipe folder  {0} created 的本地化字符串.
        /// </summary>
        internal static string RecipeFileManager_CreateFolder_RecipeFolder0Created {
            get {
                return ResourceManager.GetString("RecipeFileManager_CreateFolder_RecipeFolder0Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 recipe folder  {0} create failed 的本地化字符串.
        /// </summary>
        internal static string RecipeFileManager_CreateFolder_RecipeFolder0CreateFailed {
            get {
                return ResourceManager.GetString("RecipeFileManager_CreateFolder_RecipeFolder0CreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 recipe folder  {0} delete succeeded  的本地化字符串.
        /// </summary>
        internal static string RecipeFileManager_DeleteFolder_RecipeFolder0DeleteSucceeded {
            get {
                return ResourceManager.GetString("RecipeFileManager_DeleteFolder_RecipeFolder0DeleteSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 recipe file  {0} delete failed 的本地化字符串.
        /// </summary>
        internal static string RecipeFileManager_DeleteRecipe_RecipeFile0DeleteFailed {
            get {
                return ResourceManager.GetString("RecipeFileManager_DeleteRecipe_RecipeFile0DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 recipe file  {0} deleted 的本地化字符串.
        /// </summary>
        internal static string RecipeFileManager_DeleteRecipe_RecipeFile0DeleteSucceeded {
            get {
                return ResourceManager.GetString("RecipeFileManager_DeleteRecipe_RecipeFile0DeleteSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 recipe folder  {0} renamed {1} 的本地化字符串.
        /// </summary>
        internal static string RecipeFileManager_RenameFolder_RecipeFolder0renamed {
            get {
                return ResourceManager.GetString("RecipeFileManager_RenameFolder_RecipeFolder0renamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 recipe folder  {0} rename as {1} failed 的本地化字符串.
        /// </summary>
        internal static string RecipeFileManager_RenameFolder_RecipeFolder0RenameFailed {
            get {
                return ResourceManager.GetString("RecipeFileManager_RenameFolder_RecipeFolder0RenameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 recipe file  {0} rename failed:  the same name file already existed 的本地化字符串.
        /// </summary>
        internal static string RecipeFileManager_RenameRecipe_RecipeFile0FileExisted {
            get {
                return ResourceManager.GetString("RecipeFileManager_RenameRecipe_RecipeFile0FileExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 recipe file  {0}  renamed {1} 的本地化字符串.
        /// </summary>
        internal static string RecipeFileManager_RenameRecipe_RecipeFile0Renamed {
            get {
                return ResourceManager.GetString("RecipeFileManager_RenameRecipe_RecipeFile0Renamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 recipe file  {0} Rename {1} Failed 的本地化字符串.
        /// </summary>
        internal static string RecipeFileManager_RenameRecipe_RecipeFile0RenameFailed {
            get {
                return ResourceManager.GetString("RecipeFileManager_RenameRecipe_RecipeFile0RenameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 recipe file  {0}  save failed: file already exist 的本地化字符串.
        /// </summary>
        internal static string RecipeFileManager_SaveAsRecipe_RecipeFile0savefailed {
            get {
                return ResourceManager.GetString("RecipeFileManager_SaveAsRecipe_RecipeFile0savefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 barcode {0} is duplicated in {1} 的本地化字符串.
        /// </summary>
        internal static string RecipeFileManager_SaveRecipe_Barcode0IsDuplicatedIn1 {
            get {
                return ResourceManager.GetString("RecipeFileManager_SaveRecipe_Barcode0IsDuplicatedIn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 recipe file  {0}  save completed 的本地化字符串.
        /// </summary>
        internal static string RecipeFileManager_SaveRecipe_RecipeFile0SaveCompleted {
            get {
                return ResourceManager.GetString("RecipeFileManager_SaveRecipe_RecipeFile0SaveCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 recipe file {0} save failed 的本地化字符串.
        /// </summary>
        internal static string RecipeFileManager_SaveRecipe_RecipeFile0SaveFailed {
            get {
                return ResourceManager.GetString("RecipeFileManager_SaveRecipe_RecipeFile0SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Recipe {0} Content has Error 的本地化字符串.
        /// </summary>
        internal static string RecipeFileManager_SaveRecipe_SaveRecipeContentError {
            get {
                return ResourceManager.GetString("RecipeFileManager_SaveRecipe_SaveRecipeContentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML Schema Valid failed 的本地化字符串.
        /// </summary>
        internal static string RecipeFileManager_ValidateRecipe_XMLSchemaValidateFailed {
            get {
                return ResourceManager.GetString("RecipeFileManager_ValidateRecipe_XMLSchemaValidateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} setpoint should be in {1} and {2}， setting value {3} is not valid 的本地化字符串.
        /// </summary>
        internal static string SCManager_SetItemValue_0SetpointShouldBeIn1And2SettingValue3IsNotValid {
            get {
                return ResourceManager.GetString("SCManager_SetItemValue_0SetpointShouldBeIn1And2SettingValue3IsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to exit？ 的本地化字符串.
        /// </summary>
        internal static string ViewManager_Exit_AreYouSureYouWantToExit {
            get {
                return ResourceManager.GetString("ViewManager_Exit_AreYouSureYouWantToExit", resourceCulture);
            }
        }
    }
}
