//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MECF.Framework.UI.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MECF.Framework.UI.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The SelectedDates collection can be changed only in a multiple selection mode. Use the SelectedDate in a single selection mode. 的本地化字符串。
        /// </summary>
        internal static string Calendar_CheckSelectionMode_InvalidOperation {
            get {
                return ResourceManager.GetString("Calendar_CheckSelectionMode_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next button 的本地化字符串。
        /// </summary>
        internal static string Calendar_NextButtonName {
            get {
                return ResourceManager.GetString("Calendar_NextButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DisplayMode value is not valid. 的本地化字符串。
        /// </summary>
        internal static string Calendar_OnDisplayModePropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Calendar_OnDisplayModePropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FirstDayOfWeek value is not valid. 的本地化字符串。
        /// </summary>
        internal static string Calendar_OnFirstDayOfWeekChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Calendar_OnFirstDayOfWeekChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The SelectedDate property cannot be set when the selection mode is None. 的本地化字符串。
        /// </summary>
        internal static string Calendar_OnSelectedDateChanged_InvalidOperation {
            get {
                return ResourceManager.GetString("Calendar_OnSelectedDateChanged_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SelectedDate value is not valid. 的本地化字符串。
        /// </summary>
        internal static string Calendar_OnSelectedDateChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Calendar_OnSelectedDateChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SelectionMode value is not valid. 的本地化字符串。
        /// </summary>
        internal static string Calendar_OnSelectionModeChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Calendar_OnSelectionModeChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous button 的本地化字符串。
        /// </summary>
        internal static string Calendar_PreviousButtonName {
            get {
                return ResourceManager.GetString("Calendar_PreviousButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value is not valid. 的本地化字符串。
        /// </summary>
        internal static string Calendar_UnSelectableDates {
            get {
                return ResourceManager.GetString("Calendar_UnSelectableDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blackout Day - {0} 的本地化字符串。
        /// </summary>
        internal static string CalendarAutomationPeer_BlackoutDayHelpText {
            get {
                return ResourceManager.GetString("CalendarAutomationPeer_BlackoutDayHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calendar button 的本地化字符串。
        /// </summary>
        internal static string CalendarAutomationPeer_CalendarButtonLocalizedControlType {
            get {
                return ResourceManager.GetString("CalendarAutomationPeer_CalendarButtonLocalizedControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Day button 的本地化字符串。
        /// </summary>
        internal static string CalendarAutomationPeer_DayButtonLocalizedControlType {
            get {
                return ResourceManager.GetString("CalendarAutomationPeer_DayButtonLocalizedControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decade 的本地化字符串。
        /// </summary>
        internal static string CalendarAutomationPeer_DecadeMode {
            get {
                return ResourceManager.GetString("CalendarAutomationPeer_DecadeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Month 的本地化字符串。
        /// </summary>
        internal static string CalendarAutomationPeer_MonthMode {
            get {
                return ResourceManager.GetString("CalendarAutomationPeer_MonthMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Year 的本地化字符串。
        /// </summary>
        internal static string CalendarAutomationPeer_YearMode {
            get {
                return ResourceManager.GetString("CalendarAutomationPeer_YearMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This type of Collection does not support changes to its SourceCollection from a thread different from the Dispatcher thread. 的本地化字符串。
        /// </summary>
        internal static string CalendarCollection_MultiThreadedCollectionChangeNotSupported {
            get {
                return ResourceManager.GetString("CalendarCollection_MultiThreadedCollectionChangeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot perform copy if ClipboardCopyMode is None. 的本地化字符串。
        /// </summary>
        internal static string ClipboardCopyMode_Disabled {
            get {
                return ResourceManager.GetString("ClipboardCopyMode_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Begin Edit 的本地化字符串。
        /// </summary>
        internal static string DataGrid_BeginEditCommandText {
            get {
                return ResourceManager.GetString("DataGrid_BeginEditCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel Edit 的本地化字符串。
        /// </summary>
        internal static string DataGrid_CancelEditCommandText {
            get {
                return ResourceManager.GetString("DataGrid_CancelEditCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot change cell selection when the SelectionUnit is FullRow. 的本地化字符串。
        /// </summary>
        internal static string DataGrid_CannotSelectCell {
            get {
                return ResourceManager.GetString("DataGrid_CannotSelectCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The DisplayIndex for the DataGridColumn with Header &apos;{0}&apos; is out of range.  DisplayIndex must be greater than or equal to 0 and less than Columns.Count. 的本地化字符串。
        /// </summary>
        internal static string DataGrid_ColumnDisplayIndexOutOfRange {
            get {
                return ResourceManager.GetString("DataGrid_ColumnDisplayIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The index for the DataGridColumn with Header &apos;{0}&apos; is out of range. Index must be greater than or equal to 0 and less than Columns.Count. 的本地化字符串。
        /// </summary>
        internal static string DataGrid_ColumnIndexOutOfRange {
            get {
                return ResourceManager.GetString("DataGrid_ColumnIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commit Edit 的本地化字符串。
        /// </summary>
        internal static string DataGrid_CommitEditCommandText {
            get {
                return ResourceManager.GetString("DataGrid_CommitEditCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string DataGrid_DeleteCommandText {
            get {
                return ResourceManager.GetString("DataGrid_DeleteCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given DisplayIndex is out of range.  DisplayIndex must be greater than or equal to 0 and less than Columns.Count. 的本地化字符串。
        /// </summary>
        internal static string DataGrid_DisplayIndexOutOfRange {
            get {
                return ResourceManager.GetString("DataGrid_DisplayIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DisplayIndex is already used for other column.  DisplayIndex should be unique per column. 的本地化字符串。
        /// </summary>
        internal static string DataGrid_DuplicateDisplayIndex {
            get {
                return ResourceManager.GetString("DataGrid_DuplicateDisplayIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataGridColumn with Header &apos;{0}&apos; already exists in the Columns collection of a DataGrid. DataGrids cannot share columns and cannot contain duplicate column instances. 的本地化字符串。
        /// </summary>
        internal static string DataGrid_InvalidColumnReuse {
            get {
                return ResourceManager.GetString("DataGrid_InvalidColumnReuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The SortDescriptions added are not valid. The probable solutions are to set the CanUserSort on the Column to false, or to use SortMemberPath property on the Column, or to handle the Sorting event on DataGrid. 的本地化字符串。
        /// </summary>
        internal static string DataGrid_InvalidSortDescription {
            get {
                return ResourceManager.GetString("DataGrid_InvalidSortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot add a column with an invalid DisplayIndex to the DataGrid.Columns collection. 的本地化字符串。
        /// </summary>
        internal static string DataGrid_NewColumnInvalidDisplayIndex {
            get {
                return ResourceManager.GetString("DataGrid_NewColumnInvalidDisplayIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot add a null column to a DataGrid&apos;s column collection. 的本地化字符串。
        /// </summary>
        internal static string DataGrid_NullColumn {
            get {
                return ResourceManager.GetString("DataGrid_NullColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Items refresh of the DataGrid failed. One of the probable causes is that the SortDescriptions added are not valid, in which case probable solutions are to set the CanUserSort on the Column to false, or to use SortMemberPath property on the Column, or to handle the Sorting event on DataGrid. 的本地化字符串。
        /// </summary>
        internal static string DataGrid_ProbableInvalidSortDescription {
            get {
                return ResourceManager.GetString("DataGrid_ProbableInvalidSortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The ItemsSource for the DataGridCellsPresenter is read-only. 的本地化字符串。
        /// </summary>
        internal static string DataGrid_ReadonlyCellsItemsSource {
            get {
                return ResourceManager.GetString("DataGrid_ReadonlyCellsItemsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select All 的本地化字符串。
        /// </summary>
        internal static string DataGrid_SelectAllCommandText {
            get {
                return ResourceManager.GetString("DataGrid_SelectAllCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+A 的本地化字符串。
        /// </summary>
        internal static string DataGrid_SelectAllKey {
            get {
                return ResourceManager.GetString("DataGrid_SelectAllKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+A 的本地化字符串。
        /// </summary>
        internal static string DataGrid_SelectAllKeyDisplayString {
            get {
                return ResourceManager.GetString("DataGrid_SelectAllKeyDisplayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value should not be infinity. 的本地化字符串。
        /// </summary>
        internal static string DataGridLength_Infinity {
            get {
                return ResourceManager.GetString("DataGridLength_Infinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid type. 的本地化字符串。
        /// </summary>
        internal static string DataGridLength_InvalidType {
            get {
                return ResourceManager.GetString("DataGridLength_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current value of the SelectionUnit property on the parent DataGrid prevents rows from being selected. 的本地化字符串。
        /// </summary>
        internal static string DataGridRow_CannotSelectRowWhenCells {
            get {
                return ResourceManager.GetString("DataGridRow_CannotSelectRowWhenCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Calendar 的本地化字符串。
        /// </summary>
        internal static string DatePicker_DropDownButtonName {
            get {
                return ResourceManager.GetString("DatePicker_DropDownButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DatePickerFormat value is not valid. 的本地化字符串。
        /// </summary>
        internal static string DatePicker_OnSelectedDateFormatChanged_InvalidValue {
            get {
                return ResourceManager.GetString("DatePicker_OnSelectedDateFormatChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Calendar 的本地化字符串。
        /// </summary>
        internal static string DatePicker_WatermarkText {
            get {
                return ResourceManager.GetString("DatePicker_WatermarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 date picker 的本地化字符串。
        /// </summary>
        internal static string DatePickerAutomationPeer_LocalizedControlType {
            get {
                return ResourceManager.GetString("DatePickerAutomationPeer_LocalizedControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Enter text here&gt; 的本地化字符串。
        /// </summary>
        internal static string DatePickerTextBox_DefaultWatermarkText {
            get {
                return ResourceManager.GetString("DatePickerTextBox_DefaultWatermarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The template part {0} is not an instance of {1}. 的本地化字符串。
        /// </summary>
        internal static string DatePickerTextBox_TemplatePartIsOfIncorrectType {
            get {
                return ResourceManager.GetString("DatePickerTextBox_TemplatePartIsOfIncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The collection already contains the item. 的本地化字符串。
        /// </summary>
        internal static string SelectedCellsCollection_DuplicateItem {
            get {
                return ResourceManager.GetString("SelectedCellsCollection_DuplicateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The DataGridItem is invalid. 的本地化字符串。
        /// </summary>
        internal static string SelectedCellsCollection_InvalidItem {
            get {
                return ResourceManager.GetString("SelectedCellsCollection_InvalidItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 test value 的本地化字符串。
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This collection does not support changing values with specific indexes. 的本地化字符串。
        /// </summary>
        internal static string VirtualizedCellInfoCollection_DoesNotSupportIndexChanges {
            get {
                return ResourceManager.GetString("VirtualizedCellInfoCollection_DoesNotSupportIndexChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The collection cannot be modified. 的本地化字符串。
        /// </summary>
        internal static string VirtualizedCellInfoCollection_IsReadOnly {
            get {
                return ResourceManager.GetString("VirtualizedCellInfoCollection_IsReadOnly", resourceCulture);
            }
        }
    }
}
